---
title: "Blog Data Wrangling - Sarah Edelson, Matthew Perkins, Seamus Lawton"
output:
  html_document:
    df_print: paged
---

```{r}
# Loading Packages
library(ggplot2)
library(dplyr)
library(tidyverse)
library(rvest)
library(here)
library(readr)
library(ggnetwork)
library(datasets)
library(mdsr)
library(gapminder)
library(igraph)
library(maps)
library(wordcloud)
library(scales)
library(tidyverse) 
library(janitor)
library(tidytext)
library(wordcloud)
library(textdata)
library(DT)
library(kableExtra)
```

```{r}
# Create Individual Contributions Shiny Map
individual_contributions <- read_csv(here("Data", "IndividualContributions.csv"))

individual_contributions <- individual_contributions %>%
  pivot_longer(!State, names_to = "Candidate", values_to = "Contribution") %>%
  filter(State != "ZZ") %>%
  filter(State != "AA") %>%
  filter(State != "AE")  %>%
  filter(State != "AP")  %>%
  filter(State != "AS")  %>%
  filter(State != "GU")  %>%
  filter(State != "MP")  %>%
  filter(State != "OT")  %>%
  filter(State != "PR")  %>%
  mutate(candidate_cleaned = (case_when(
         str_detect(Candidate, "BIDEN, JOSEPH R JR") ~ "Joe Biden",
         str_detect(Candidate, "BLOOMBERG, MICHAEL R.") ~ "Michael Bloomberg",
         str_detect(Candidate, "HARRIS, KAMALA D.") ~ "Kamala Harris",
         str_detect(Candidate, "KLOBUCHAR, AMY J.") ~ "Amy Klobuchar",
         str_detect(Candidate, "SANDERS, BERNARD") ~ "Bernie Sanders",
         str_detect(Candidate, "STEYER, TOM") ~ "Tom Steyer",
         str_detect(Candidate, "TRUMP, DONALD J.") ~ "Donald Trump",
         str_detect(Candidate, "WARREN, ELIZABETH") ~ "Elizabeth Warren",
         str_detect(Candidate, "YANG, ANDREW MR.") ~ "Andrew Yang"
         )))
  

state_info <- data.frame(state_full = tolower(state.name) , State = state.abb,
                         Region = state.region)

usa_states <- map_data(map = "state"
                       , region = ".")

contributions_map <- individual_contributions %>%
  left_join(state_info, by = "State") %>%
  right_join(usa_states, by = c("state_full" = "region"))
```


```{r}
# Create Network for independent expenditures
independent_expenditures <- read_csv(here("Data", "IndependentExpenditures.csv"))

independent_expenditures <- independent_expenditures %>%
  mutate(candidate_cleaned_ie = (case_when(
         str_detect(candidate_name, "BIDEN, JOSEPH R JR") ~ "Joe Biden",
         str_detect(candidate_name, "BLOOMBERG, MICHAEL R.") ~ "Michael Bloomberg",
         str_detect(candidate_name, "HARRIS, KAMALA D.") ~ "Kamala Harris",
         str_detect(candidate_name, "KLOBUCHAR, AMY J.") ~ "Amy Klobuchar",
         str_detect(candidate_name, "SANDERS, BERNARD") ~ "Bernie Sanders",
         str_detect(candidate_name, "STEYER, TOM") ~ "Tom Steyer",
         str_detect(candidate_name, "TRUMP, DONALD J.") ~ "Donald Trump",
         str_detect(candidate_name, "WARREN, ELIZABETH") ~ "Elizabeth Warren",
         str_detect(candidate_name, "YANG, ANDREW MR.") ~ "Andrew Yang"
         )))
  

independent_expenditures_large <- independent_expenditures %>%
  mutate(committee_cleaned = (case_when(
         str_detect(committee_name, "DEFENDING DEMOCRACY TOGETHER") ~ (paste("DEFENDING", "DEMOCRACY", "TOGETHER", sep="\n")),
         str_detect(committee_name, "AB PAC") ~ "AB PAC",
         str_detect(committee_name, "THE LINCOLN PROJECT") ~ "THE LINCOLN PROJECT",
         str_detect(committee_name, "GREAT AMERICA PAC") ~ "GREAT AMERICA PAC.",
         str_detect(committee_name, "THE COMMITTEE TO DEFEND THE PRESIDENT") ~ (paste("THE COMMITTEE", "TO DEFEND", "THE PRESIDENT", sep = "\n")),
         str_detect(committee_name, "LCV VICTORY FUND") ~ "LCV VICTORY FUND",
         str_detect(committee_name, "PRIORITIES USA ACTION") ~ "PRIORITIES USA ACTION",
         str_detect(committee_name, "FF PAC") ~ "FF PAC",
         str_detect(committee_name, "INDEPENDENCE USA PAC") ~ "INDEPENDENCE USA PAC",
         str_detect(committee_name, "BLACK PAC") ~ "BLACK PAC",
         str_detect(committee_name, "RESTORATION PAC") ~ "RESTORATION PAC",
         str_detect(committee_name, "AMERICA FIRST ACTION, INC.") ~ (paste("AMERICA FIRST","ACTION, INC.", sep="\n")),
         str_detect(committee_name, "UNITE THE COUNTRY") ~ "UNITE THE COUNTRY",
         str_detect(committee_name, "NRA VICTORY FUND, INC.") ~ "NRA VICTORY FUND, INC.",
         str_detect(committee_name, "CLUB FOR GROWTH ACTION") ~ "CLUB FOR GROWTH ACTION",
         str_detect(committee_name, "NEXTGEN CLIMATE ACTION COMMITTEE") ~ (paste("NEXTGEN CLIMATE", "ACTION COMMITTEE", sep="\n")),
         str_detect(committee_name, "PRESERVE AMERICA PAC") ~ "PRESERVE AMERICA PAC")
         ))

independent_expenditures_large <- independent_expenditures_large %>%
  select(committee_cleaned, candidate_cleaned_ie, total, support_oppose_indicator) %>%
  filter(total >= 10000000)  %>%
  filter(candidate_cleaned_ie == "Donald Trump" | candidate_cleaned_ie == "Joe Biden")

set.seed(15)
g_expenditures <- graph_from_data_frame(independent_expenditures_large, directed = TRUE)

expenditures_network <- ggnetwork(g_expenditures) %>%
  mutate(candidate = case_when(name == "Donald Trump" ~ "Donald Trump", 
                               name == "Joe Biden" ~ "Joe Biden",
                               TRUE ~ ""))


# Color by support or oppose
ggplot(data = expenditures_network, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(aes(size = total/1000000, color = support_oppose_indicator)) + geom_nodes() +
  geom_nodelabel(data = filter(expenditures_network, name!= "Donald Trump" & name != "Joe Biden"), aes(label = name), color = "black", size = 10) +
  geom_nodelabel(data = filter(expenditures_network, name == "Donald Trump"), aes(label = name), color = "blue", size = 14) +
  geom_nodelabel(data = filter(expenditures_network, name == "Joe Biden"), aes(label = name), color = "blue", size = 14) +
  theme_blank() +
  scale_color_manual(values=c("red2", "slategray")) +
  labs(size = "Contribution Size (millions)") +
  labs(color = "Support or Oppose Candidate") +
  ggtitle("Independent Expenditures Over 10 million") +
  theme(plot.title = element_text(size = 30)) +
  theme(legend.title = element_text(size = 30)) +
  theme(legend.text = element_text(size = 30)) +
  theme(legend.position = "bottom")
```

```{r}
# Interactive Table for all independent expenditures
independent_expenditures %>%
  select(candidate_name, committee_name, total, support_oppose_indicator) %>%
  arrange(desc(total)) %>%
  datatable(
    head(iris),
    caption = "All Independent Expenditures")
```


```{r}
# Interactive Network
library(visNetwork)
library(gdata)

make_network <- function(network) {

name_vec <- name_vec <- c.factor(unique(c.factor(unique(independent_expenditures$candidate_name), 
                     unique(independent_expenditures$committee_name))))


from <- independent_expenditures$committee_name
to <- independent_expenditures$candidate_name

edges <- data.frame(from = from, to = to, value = support_oppose_indicator)
nodes <- data.frame(id = name_vec, label = name_vec, group = name_vec)

# network visualizations
  visNetwork(nodes, edges, height = "500px", width = "100%")  %>% 
    visNodes(shape = "dot") %>%  
             # arrows show exports
    visEdges(arrows = "to", arrowStrikethrough = F, smooth = T, physics = F) %>%
    # hide other nodes and incoming edges when a node is selected
    visOptions(highlightNearest = list(enabled = T, degree = 0)) %>%
    # add navigation buttons and allow multiple nodes to be selected at once
    visInteraction(navigationButtons = TRUE, multiselect = TRUE) %>%
  visLayout(randomSeed = 17)
  }
```

