---
title: "Blog Data Wrangling - Sarah Edelson, Matthew Perkins, Seamus Lawton"
output: pdf_document
---

```{r}
# Loading Packages
library(dplyr)
library(tidyverse)
library(rvest)
library(here)
library(readr)
library(ggnetwork)
library(datasets)
library(mdsr)
library(gapminder)
library(igraph)
```

```{r}
# Create Individual Contributions Map
individual_contributions <- read_csv(here("Data", "IndividualContributions.csv"))

individual_contributions <- individual_contributions %>%
  pivot_longer(!State, names_to = "Candidate", values_to = "Contribution")
  


state_info <- data.frame(state_full = tolower(state.name) , State = state.abb,
                         Region = state.region)

usa_states <- map_data(map = "state"
, region = ".")

contributions_map <- individual_contributions %>%
  left_join(state_info, by = "State") %>%
  right_join(usa_states, by = c("state_full" = "region"))

```


```{r}
# Create Network for independent expenditures
independent_expenditures <- read_csv(here("Data", "IndependentExpenditures.csv"))

independent_expenditures_large <- independent_expenditures %>%
  select(committee_name, candidate_name, total, support_oppose_indicator) %>%
  filter(total >= 2000000)  %>%
  filter(candidate_name == "TRUMP, DONALD J" | candidate_name == "BIDEN, JOSEPH R JR")

g_expenditures <- graph_from_data_frame(independent_expenditures_large, directed = TRUE)

expenditures_network <- ggnetwork(g_expenditures)

ggplot(data = expenditures_network, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(arrow=arrow(type="closed", length=unit(6,"pt")), color = support_oppose_indicator,
  aes(size = total)) + geom_nodes() +
  geom_nodelabel(aes(label = name)) +
  theme_blank()

```